objective:
  - TV1D[data_fit=quad,delta=0,reg=[0.5, 0.1]]
  - TV1D[data_fit=huber,delta=0.9,reg=[0.5, 0.1]]
dataset:
  - Simulated[n_samples=[400, 750],n_features=500,type_A=random,num_block=[10, 50],type_x=block]
solver:
  - admm analysis
  - celer synthesis
  - Chambolle-Pock analysis
  - Chambolle-Pock PD-split analysis
  - CondatVu analysis
  - Dual PGD analysis
  - FP synthesis
  - Primal PGD synthesis*
  - Primal PGD analysis
  - skglm synthesis
n-repetitions: 5
timeout: 6000
max-runs: 200

output: tv1d_neurips
