objective:
  - TV1D[data_fit=quad,delta=0.9,reg=0.5]
  - TV1D[data_fit=huber,delta=0.9,reg=0.5]
dataset:
  - Simulated sinusoidal[sigma=0.1,mu=0,n_features=500,n_samples=400,type_A=identity]
  - Simulated blocked[sigma=0.1,mu=0,n_features=500,n_samples=400,type_A=identity,num_block=10]
#solver:
#  - all
n-repetitions: 1
timeout: 1200
max-runs: 100
