objective:
  - TV1D[data_fit=quad,delta=0,reg=0.1]
  - TV1D[data_fit=huber,delta=0.9,reg=0.1]
dataset:
  - Simulated[n_samples=40,n_features=25,type_A=conv,type_x=block,type_n=laplace]
  - Simulated[n_samples=40,n_features=40,type_A=random,type_x=block,type_n=gaussian]
solver:
  - admm analysis
  - celer synthesis
  - Chambolle-Pock PD-split analysis
  - CondatVu analysis
  - Dual PGD analysis
  - FP synthesis
  - Primal PGD synthesis*
  - Primal PGD analysis
  - skglm synthesis
n-repetitions: 1
timeout: 60
max-runs: 50
