objective-filter:
  - TV1D[data_fit=quad,delta=0.9,reg=0.5]
  - TV1D[data_fit=huber,delta=0.9,reg=0.5]
dataset:
  - Simulated blocked[sigma=0.1,mu=0,n_features=50,n_samples=40,type_A=random_nonsquare, num_block=3]
#solver:
#  - Celer synthesis
#  - ADMM analysis and synthesis
n-repetitions: 1
timeout: 50
max-runs: 50
